// The hundred people on the wall. Each is a specific individual with concrete
// traits Jev can reason from; it reads literally, so every field is plain fact
// about this one person, never a group. Field names are the ones the questions
// reference by path, so they are part of the wire contract with Jev.

// A type alias, not an interface, so it stays assignable to the SDK's JSON
// state type.
export type Persona = {
  name: string;
  age: number;
  job: string;
  lives_in: string;
  temperament: string;
  cares_about: string;
  how_they_read: string;
};

export const PERSONAS: readonly Persona[] = [
  {
    name: "Rosa Delgado",
    age: 67,
    job: "retired school secretary living on a fixed pension",
    lives_in: "San Antonio, Texas",
    temperament: "warm, chatty, slow to anger, quick to worry about money",
    cares_about: "her four grandchildren, her church choir, making the pension stretch to the end of the month",
    how_they_read: "reads everything twice on a phone her daughter set up, distrusts anything with fine print, and asks her daughter before clicking on anything",
  },
  {
    name: "Kwame Mensah",
    age: 29,
    job: "backend software engineer at a payments startup",
    lives_in: "Accra, Ghana",
    temperament: "analytical, dry humour, hard to impress",
    cares_about: "shipping reliable code, mobile-money adoption across West Africa, Hearts of Oak football club",
    how_they_read: "skims for the concrete number or the API change, ignores marketing adjectives entirely, and gets his news from developer forums and group chats",
  },
  {
    name: "Linnea Berg",
    age: 41,
    job: "dairy farmer running sixty cows with her husband",
    lives_in: "rural Jämtland, Sweden",
    temperament: "practical, blunt, unsentimental",
    cares_about: "the milk price, the weather forecast, the school bus running for her two kids",
    how_they_read: "English is her second language; she prefers short sentences, reads on a phone in the milking parlour, and has no patience for hype or long paragraphs",
  },
  {
    name: "Daryl Whitfield",
    age: 52,
    job: "long-haul truck driver, thirty years on the road",
    lives_in: "Amarillo, Texas",
    temperament: "steady, quiet, assumes companies are out to get him",
    cares_about: "diesel prices, days at home with his wife, his old dog Duke",
    how_they_read: "listens to audiobooks and talk radio more than he reads; skims messages on his phone at truck stops and only finishes the short ones",
  },
  {
    name: "Priya Raman",
    age: 24,
    job: "first-year internal-medicine resident",
    lives_in: "Chicago, Illinois",
    temperament: "exhausted, precise, impatient with fluff",
    cares_about: "her patients, six hours of sleep, paying down two hundred thousand dollars of medical-school loans",
    how_they_read: "reads very fast between pages from the ward and notices immediately when a message leaves out the one fact that matters",
  },
  {
    name: "Tomasz Nowak",
    age: 38,
    job: "self-employed electrician with two apprentices",
    lives_in: "Kraków, Poland",
    temperament: "even-tempered, proud of his craft, fair-minded",
    cares_about: "being paid on time, Wisła Kraków, his daughter getting into a good secondary school",
    how_they_read: "reads Polish fluently and English slowly; prices and dates jump out first, and everything else he reads later, if at all, on the van's dashboard phone",
  },
  {
    name: "Ada Osei",
    age: 19,
    job: "nursing student who works weekends at a café",
    lives_in: "Manchester, England",
    temperament: "cheerful, easily excited, quick to share things with friends",
    cares_about: "her friend group, TikTok trends, passing anatomy, the café's tips jar",
    how_they_read: "reads the headline and the first line on her phone, then decides; forwards anything funny or outrageous to the group chat within seconds",
  },
  {
    name: "George Papadakis",
    age: 74,
    job: "retired merchant-ship engineer",
    lives_in: "Piraeus, Greece",
    temperament: "gruff, direct, dislikes being sold to",
    cares_about: "his pension arriving on time, his grandchildren, afternoon chess at the kafeneio",
    how_they_read: "reads slowly and thoroughly on a desktop computer; treats exclamation marks and the words 'exciting news' as a warning sign, and reads English from his shipping years",
  },
  {
    name: "Maribel Cruz",
    age: 45,
    job: "hotel housekeeping supervisor managing a team of twelve",
    lives_in: "Orlando, Florida",
    temperament: "organised, protective of her team, tired but good-humoured",
    cares_about: "fair schedules, overtime pay, her son's baseball season",
    how_they_read: "reads on her phone between floors, prefers plain words in English or Spanish, and gets irritated by messages that hide the point behind pleasantries",
  },
  {
    name: "Henrik Dahl",
    age: 33,
    job: "product manager at a fintech company",
    lives_in: "Copenhagen, Denmark",
    temperament: "curious, optimistic, comfortable with jargon",
    cares_about: "growth metrics, cycling to work, clean interface design, product newsletters",
    how_they_read: "reads a lot and quickly on a laptop and a phone; forgives buzzwords when the underlying idea is clear and shares interesting product news with his team",
  },
  {
    name: "Yuki Tanaka",
    age: 28,
    job: "freelance illustrator for book covers and games",
    lives_in: "Osaka, Japan",
    temperament: "quiet, sensitive, values politeness highly",
    cares_about: "creative freedom, long-term clients, her two cats, fair payment terms",
    how_they_read: "reads English carefully as a second language on a tablet; abrupt or pushy tone reads as rude to her, and she rarely reposts anything",
  },
  {
    name: "Clarence Bell",
    age: 61,
    job: "Baptist pastor of a three-hundred-member church",
    lives_in: "Birmingham, Alabama",
    temperament: "warm, deliberate, principled",
    cares_about: "his congregation, treating people with dignity, straight dealing, his wife's health",
    how_they_read: "reads the whole thing, often printed out, and weighs the intent behind the words more than the words themselves; distrusts anything that flatters",
  },
  {
    name: "Sofia Marchetti",
    age: 36,
    job: "high-school literature teacher",
    lives_in: "Bologna, Italy",
    temperament: "passionate, opinionated, quick to laugh",
    cares_about: "her students, good food, precise language, her book club",
    how_they_read: "reads critically in Italian and English, notices sloppy or manipulative wording at once, and says so; follows the news on public radio",
  },
  {
    name: "Jamal Robinson",
    age: 22,
    job: "warehouse picker who records rap at night",
    lives_in: "Atlanta, Georgia",
    temperament: "energetic, restless, hates being talked down to",
    cares_about: "his music, his friends, saving for a used car, his little sister",
    how_they_read: "reads on his phone in short bursts between shifts; long paragraphs lose him, anything preachy gets closed, and a good line gets screenshotted",
  },
  {
    name: "Margaret O'Connell",
    age: 79,
    job: "retired public librarian, widowed",
    lives_in: "Cork, Ireland",
    temperament: "gentle, patient, wry",
    cares_about: "her book club, her rose garden, letters from her son in Australia",
    how_they_read: "reads everything to the end on paper or a large-print tablet and remembers the exact wording; distrusts anything that says 'act now' and phones her son about suspicious messages",
  },
  {
    name: "Diego Fernández",
    age: 31,
    job: "ride-share driver studying accounting at night",
    lives_in: "Mexico City, Mexico",
    temperament: "upbeat, hustling, careful with every peso",
    cares_about: "fuel costs, his exam dates, his mother's diabetes care",
    how_they_read: "reads Spanish first; English messages take him a second pass on his phone between rides, and he looks for the cost before anything else",
  },
  {
    name: "Anneliese Weber",
    age: 55,
    job: "tax advisor with her own small practice",
    lives_in: "Stuttgart, Germany",
    temperament: "exacting, formal, distrusts vagueness",
    cares_about: "accuracy, rules being followed, punctuality, her clients' trust",
    how_they_read: "reads the fine print before the headline, in German or English, and judges the sender by whether the terms and dates are complete",
  },
  {
    name: "Tyler Brooks",
    age: 17,
    job: "high-school junior with a part-time job at a bike shop",
    lives_in: "Boise, Idaho",
    temperament: "sarcastic, very online, quick to call things cringe",
    cares_about: "gaming with friends, skateboarding, not being bored, his Discord servers",
    how_they_read: "skims and judges the tone in two seconds; corporate cheerfulness is instantly funny to him and gets screenshotted for the group",
  },
  {
    name: "Fatima Al-Sayed",
    age: 43,
    job: "community pharmacist",
    lives_in: "Amman, Jordan",
    temperament: "careful, courteous, family-focused",
    cares_about: "patient safety, her three children, saving for a house, her professional reputation",
    how_they_read: "reads English well from her pharmacy training; prefers formal, complete information and is put off by casual or joking tone in business messages",
  },
  {
    name: "Bruce Kowalski",
    age: 58,
    job: "union plumber",
    lives_in: "Pittsburgh, Pennsylvania",
    temperament: "loyal, blunt, allergic to corporate speak",
    cares_about: "his pension, the Steelers, being treated fairly, his union local",
    how_they_read: "reads short things only, usually on a flip-phone-sized screen; a wall of text or a word like 'synergy' gets the message ignored",
  },
  {
    name: "Chen Wei",
    age: 26,
    job: "data analyst at an e-commerce company",
    lives_in: "Shenzhen, China",
    temperament: "ambitious, methodical, privately anxious",
    cares_about: "getting promoted, saving money, his parents' expectations, his weekly badminton game",
    how_they_read: "reads technical English well from work; casual slang and wordplay confuse him and he re-reads them, sometimes with a translation app",
  },
  {
    name: "Beatriz Souza",
    age: 39,
    job: "emergency-room nurse on twelve-hour shifts",
    lives_in: "São Paulo, Brazil",
    temperament: "compassionate, tired, fiercely practical",
    cares_about: "her patients, her two kids, catching the right bus home, her mother's rent",
    how_they_read: "reads Portuguese natively and English slowly, on a cracked phone screen during breaks; she trusts colleagues over anything official",
  },
  {
    name: "Nigel Hartley",
    age: 66,
    job: "retired barrister",
    lives_in: "Bath, England",
    temperament: "precise, dry, easily irritated by imprecision",
    cares_about: "good wine, county cricket, the Times crossword, his grandchildren's schooling",
    how_they_read: "reads for logical gaps and usually finds them; an unsupported claim annoys him more than bad news, and he writes letters of complaint",
  },
  {
    name: "Aisha Bello",
    age: 30,
    job: "owner of a fabric shop in a busy market",
    lives_in: "Lagos, Nigeria",
    temperament: "shrewd, warm, decisive",
    cares_about: "cash flow, reliable suppliers, her church women's group, her younger brother's school fees",
    how_they_read: "reads WhatsApp messages fast on her phone all day and judges any seller by whether they state a price up front",
  },
  {
    name: "Ryan Mitchell",
    age: 35,
    job: "firefighter",
    lives_in: "Sacramento, California",
    temperament: "calm, physical, low tolerance for drama",
    cares_about: "his crew, his two kids, weekend fishing, his mortgage",
    how_they_read: "reads the first sentence on his phone and decides whether the rest matters; usually it doesn't, and he never forwards anything",
  },
  {
    name: "Elena Petrova",
    age: 48,
    job: "piano teacher at a music school",
    lives_in: "St. Petersburg, Russia",
    temperament: "reserved, cultured, dislikes vulgarity",
    cares_about: "her students' progress, chamber music, her elderly mother, her small apartment",
    how_they_read: "reads English well from decades of scores and correspondence; hype and slang put her off immediately, and she reads on a laptop, never a phone",
  },
  {
    name: "Marcus Lindqvist",
    age: 44,
    job: "venture capital partner",
    lives_in: "Stockholm, Sweden",
    temperament: "confident, fast, impatient with slow decisions",
    cares_about: "returns, strong founders, his marathon time, his fund's next raise",
    how_they_read: "skims on his phone between meetings; wants the number and the ask in the first line and drops anything that makes him hunt for it",
  },
  {
    name: "Gloria Nakamura",
    age: 70,
    job: "retired flight attendant",
    lives_in: "Honolulu, Hawaii",
    temperament: "sociable, upbeat, forgiving",
    cares_about: "her hula group, her grandchildren, morning ocean swims, her friends' birthdays",
    how_they_read: "reads on an iPad with the text enlarged, believes most of what she reads, and shares anything cheerful with her friends on Facebook",
  },
  {
    name: "Samuel Adeyemi",
    age: 27,
    job: "Anglican seminarian",
    lives_in: "Ibadan, Nigeria",
    temperament: "thoughtful, earnest, slow to judge",
    cares_about: "his faith, his neighbourhood, school fees for his younger siblings, his reading",
    how_they_read: "reads carefully on a cheap Android phone and looks for sincerity; a message that respects the reader earns his trust, a boastful one loses it",
  },
  {
    name: "Hannah Cohen",
    age: 32,
    job: "public defender",
    lives_in: "Brooklyn, New York",
    temperament: "sharp, skeptical, protective of the underdog",
    cares_about: "her clients, fairness, an occasional full night of sleep, her running group",
    how_they_read: "reads for what the sender is hiding and assumes a polished message has a catch; reads on a phone on the subway and rarely shares",
  },
  {
    name: "Lars Eriksen",
    age: 62,
    job: "cod fisherman with his own small boat",
    lives_in: "Lofoten, Norway",
    temperament: "taciturn, weather-hardened, patient",
    cares_about: "fishing quotas, his boat's engine, his grandson, the weather",
    how_they_read: "reads Norwegian; English only when it is short, on a phone with a cracked screen, and ignores anything that sounds like advertising",
  },
  {
    name: "Mei-Ling Chang",
    age: 37,
    job: "owner of a family restaurant with twelve staff",
    lives_in: "Vancouver, Canada",
    temperament: "hardworking, direct, always calculating margins",
    cares_about: "food costs, keeping good staff, her regulars, her parents who founded the place",
    how_they_read: "reads email at one in the morning after closing; anything without a clear ask or a number gets deleted, and she never has time to share",
  },
  {
    name: "Ahmed Hassan",
    age: 50,
    job: "taxi driver",
    lives_in: "Cairo, Egypt",
    temperament: "talkative, proud, quick-tempered but quick to forgive",
    cares_about: "his family, football, the price of petrol, his daughter's wedding",
    how_they_read: "reads Arabic fluently; English messages he reads slowly on his phone and often asks his son to explain, and he repeats good stories to every passenger",
  },
  {
    name: "Olivia Grant",
    age: 23,
    job: "marketing intern at a beverage brand",
    lives_in: "Austin, Texas",
    temperament: "enthusiastic, trend-aware, a little insecure",
    cares_about: "her career, her follower count, weekend brunch, getting hired full time",
    how_they_read: "reads for tone and vibe on her phone; admires clever copy, shares it when it is on brand, and studies brands that do it well",
  },
  {
    name: "Walter Schmidt",
    age: 82,
    job: "retired tool-and-die machinist",
    lives_in: "Milwaukee, Wisconsin",
    temperament: "stubborn, frugal, loyal to old brands",
    cares_about: "his late wife's garden, the VFW post, his 1998 Buick, his monthly budget",
    how_they_read: "reads the newspaper cover to cover; suspicious of anything on a screen and of any company changing its terms, and calls his son about anything that looks like a bill",
  },
  {
    name: "Ingrid Haugen",
    age: 40,
    job: "kindergarten teacher",
    lives_in: "Bergen, Norway",
    temperament: "patient, kind, easily moved",
    cares_about: "the children in her class, hiking, fairness, her parents' farm",
    how_they_read: "reads slowly and completely, in Norwegian or English; harsh wording makes her sad rather than angry, and she shares things she finds touching",
  },
  {
    name: "Rafael Ortiz",
    age: 29,
    job: "line cook at a busy restaurant",
    lives_in: "Miami, Florida",
    temperament: "fast, funny, thick-skinned",
    cares_about: "the kitchen crew, his motorcycle, Sunday dinner at his grandmother's, his tips",
    how_they_read: "reads his phone in the walk-in fridge; if the point is not in the first line, he is out, and anything funny goes to the crew chat",
  },
  {
    name: "Deborah Klein",
    age: 56,
    job: "hospital operations administrator",
    lives_in: "Cleveland, Ohio",
    temperament: "efficient, guarded, budget-focused",
    cares_about: "compliance, her staff, her aging parents, her department's budget",
    how_they_read: "reads for liability and cost before anything else, on a desktop between meetings, and assumes any change costs money; forwards only to legal",
  },
  {
    name: "Kenji Watanabe",
    age: 34,
    job: "logistics coordinator at a trading company",
    lives_in: "Tokyo, Japan",
    temperament: "dutiful, polite, risk-averse",
    cares_about: "job security, his long commute, his newborn daughter, his company's reputation",
    how_they_read: "reads business English well; informal or pushy tone makes him uneasy and less likely to believe the message, and he reads on the train",
  },
  {
    name: "Amara Okafor",
    age: 21,
    job: "computer-science student on a scholarship",
    lives_in: "Nairobi, Kenya",
    temperament: "bright, ambitious, wary of being ripped off",
    cares_about: "scholarships, learning to code well, her mother's grocery shop, her study group",
    how_they_read: "reads fast on a laptop and a phone and first checks who is asking for money or data; shares useful things with her study group",
  },
  {
    name: "Frank Delaney",
    age: 47,
    job: "insurance claims adjuster",
    lives_in: "Omaha, Nebraska",
    temperament: "methodical, unexcitable, quietly kind",
    cares_about: "doing things by the book, his bowling league, his daughter's college fund",
    how_they_read: "reads every line on a desktop and expects the fine print to matter more than the headline; rarely shares anything and never in a hurry",
  },
  {
    name: "Zara Khan",
    age: 26,
    job: "junior hospital doctor",
    lives_in: "Birmingham, England",
    temperament: "quick, dry, overworked",
    cares_about: "her patients, her NHS colleagues, a weekend off, her medical exams",
    how_they_read: "reads in two-second glances on her phone between tasks; jargon from outside medicine reads as noise, and she shares jokes with colleagues",
  },
  {
    name: "Pedro Alves",
    age: 63,
    job: "olive farmer on land his father farmed",
    lives_in: "Alentejo, Portugal",
    temperament: "slow-talking, stoic, distrustful of city people",
    cares_about: "the harvest, water for the trees, his grandchildren, the co-operative's prices",
    how_they_read: "reads Portuguese on paper and on an old phone; barely reads English and gives up on it quickly, and asks his daughter about anything official",
  },
  {
    name: "Naomi Feldman",
    age: 38,
    job: "stay-at-home mother of three",
    lives_in: "Teaneck, New Jersey",
    temperament: "organised, community-minded, tired",
    cares_about: "her kids' school, keeping a kosher kitchen on a budget, her parents, the neighbourhood email list",
    how_they_read: "reads on her phone while cooking; a clear ask gets action, vagueness gets ignored, and anything useful gets forwarded to the other mothers",
  },
  {
    name: "Oskar Novak",
    age: 30,
    job: "independent game developer",
    lives_in: "Prague, Czech Republic",
    temperament: "playful, cynical about marketing, tech-savvy",
    cares_about: "finishing his game, good coffee, his dog, his small community of players",
    how_they_read: "reads fast on a laptop and mocks buzzwords out loud; respects a message that states a real trade-off, and posts bad marketing to his followers as a joke",
  },
  {
    name: "Lucía Herrera",
    age: 71,
    job: "retired seamstress",
    lives_in: "Seville, Spain",
    temperament: "devout, warm, easily worried",
    cares_about: "her grandchildren, her parish, her blood pressure, her late husband's pension",
    how_they_read: "reads Spanish on paper; does not read English at all and asks a neighbour to translate, and worries about any message she cannot understand",
  },
  {
    name: "Isaac Thompson",
    age: 42,
    job: "high-school chemistry teacher",
    lives_in: "Portland, Oregon",
    temperament: "thoughtful, earnest, a little preachy",
    cares_about: "his students, climate policy, cycling, honest public debate",
    how_they_read: "reads critically on a laptop and values evidence and honesty over polish; distrusts anything with no source, and shares articles with a comment of his own",
  },
  {
    name: "Mira Zupan",
    age: 19,
    job: "apprentice hairdresser",
    lives_in: "Ljubljana, Slovenia",
    temperament: "bubbly, social, fashion-focused",
    cares_about: "her clients, her Instagram, going out on Fridays, saving for a scooter",
    how_they_read: "reads casual English from social media on her phone; formal or technical language bores her within a sentence, and she reposts things that look good",
  },
  {
    name: "Robert Chen",
    age: 59,
    job: "orthopaedic surgeon with a private practice",
    lives_in: "Houston, Texas",
    temperament: "confident, busy, blunt",
    cares_about: "surgical outcomes, his practice, Saturday golf, his daughters' careers",
    how_they_read: "reads the first and last sentence only, on his phone between cases; anything vague or long gets deleted, and his assistant handles the rest",
  },
  {
    name: "Bintou Diallo",
    age: 35,
    job: "market trader selling vegetables",
    lives_in: "Dakar, Senegal",
    temperament: "resilient, quick-witted, cautious with money",
    cares_about: "her stall, her children, her savings circle, her supplier's prices",
    how_they_read: "reads French on her phone; English only in short pieces, and she trusts a voice note from someone she knows more than any written text",
  },
  {
    name: "Ethan Park",
    age: 31,
    job: "UX designer at a software company",
    lives_in: "Seoul, South Korea",
    temperament: "meticulous, calm, quietly opinionated",
    cares_about: "craft, the people who use his designs, his cat, design writing",
    how_they_read: "reads English well on a laptop and notices when copy is cluttered, condescending, or trying too hard; collects examples of good and bad writing",
  },
  {
    name: "Judith Marsh",
    age: 68,
    job: "retired district nurse",
    lives_in: "Sheffield, England",
    temperament: "kind, no-nonsense, protective of others",
    cares_about: "the NHS, her grandchildren, people being treated fairly, her allotment",
    how_they_read: "reads fully on a tablet; anything that smells like a scam makes her angry on behalf of the people it would fool, and she warns her friends",
  },
  {
    name: "Carlos Mendoza",
    age: 40,
    job: "construction foreman on commercial sites",
    lives_in: "Phoenix, Arizona",
    temperament: "direct, loyal, tired of paperwork",
    cares_about: "his crew's safety, finishing on schedule, his kids, his truck payments",
    how_they_read: "reads short messages on his phone on site; skips anything that reads like a legal notice, and forwards safety notices to the crew",
  },
  {
    name: "Sven Larsson",
    age: 25,
    job: "PhD student in particle physics",
    lives_in: "Uppsala, Sweden",
    temperament: "analytical, introverted, pedantic",
    cares_about: "his thesis, board games, precise claims, his stipend lasting",
    how_they_read: "reads carefully on a laptop and objects out loud to imprecise or exaggerated statements; checks sources before believing anything",
  },
  {
    name: "Grace Mwangi",
    age: 52,
    job: "primary-school headteacher",
    lives_in: "Nakuru, Kenya",
    temperament: "firm, caring, a community leader",
    cares_about: "her pupils, the school's funding, her church, her staff's morale",
    how_they_read: "reads formal English closely on her phone and expects a respectful tone; flippancy lowers her opinion of the sender, and she passes serious news to parents",
  },
  {
    name: "Leo Rossi",
    age: 28,
    job: "bartender auditioning for acting roles",
    lives_in: "Los Angeles, California",
    temperament: "charming, distractible, optimistic",
    cares_about: "his next audition, tips, his friends, his headshots",
    how_they_read: "reads on his phone behind the bar; reacts to the emotional tone in a second, rarely finishes, and tells the story to whoever is at the bar",
  },
  {
    name: "Halima Yusuf",
    age: 46,
    job: "civil servant in the state housing office",
    lives_in: "Kano, Nigeria",
    temperament: "dignified, patient, rule-following",
    cares_about: "her community, her children's education, her faith, doing her job properly",
    how_they_read: "reads formal English well on a desktop at work; slang and jokes make a message seem unserious to her, and she does not forward gossip",
  },
  {
    name: "Patrick O'Brien",
    age: 64,
    job: "dairy farmer",
    lives_in: "County Kerry, Ireland",
    temperament: "wry, weathered, suspicious of Dublin and of banks",
    cares_about: "the milk price, the land staying in the family, the parish, the local GAA club",
    how_they_read: "reads slowly on a phone his son bought him and would rather get a phone call; assumes a change announced by letter is bad for him",
  },
  {
    name: "Aiko Suzuki",
    age: 22,
    job: "economics student in her final year",
    lives_in: "Kyoto, Japan",
    temperament: "polite, studious, socially cautious",
    cares_about: "her grades, job hunting, her small circle of friends, her part-time tutoring",
    how_they_read: "reads academic English well; casual English she reads carefully on her phone and does not always catch jokes, and she seldom shares",
  },
  {
    name: "Malik Johnson",
    age: 36,
    job: "barber who owns his shop",
    lives_in: "Detroit, Michigan",
    temperament: "sociable, streetwise, proud",
    cares_about: "his shop, his neighbourhood, his eight-year-old son, his regulars",
    how_they_read: "reads fast on his phone between clients; respects a straight talker, dismisses anyone who sounds like a hustler, and debates the news in the shop",
  },
  {
    name: "Ingeborg Fischer",
    age: 75,
    job: "retired pharmacist",
    lives_in: "Vienna, Austria",
    temperament: "formal, exacting, well-read",
    cares_about: "her garden, the opera season, her grandchildren's manners, correct German",
    how_they_read: "reads German and English precisely on paper and a desktop; considers exclamation marks and capital letters vulgar, and never forwards anything",
  },
  {
    name: "Jake Turner",
    age: 27,
    job: "oil-rig floorhand",
    lives_in: "Odessa, Texas",
    temperament: "tough, loyal, unimpressed by talk",
    cares_about: "his paycheck, his truck, his girlfriend, the next hitch",
    how_they_read: "reads his phone between shifts; assumes anything from a company is written against him, and shares only with the guys on the rig",
  },
  {
    name: "Nadia Ivanova",
    age: 33,
    job: "Russian-to-English translator",
    lives_in: "Berlin, Germany",
    temperament: "precise, curious, culturally alert",
    cares_about: "language, her expatriate friends, news from home, her freelance rates",
    how_they_read: "reads every word on a laptop and notices shifts in tone and register that most readers miss; collects badly translated marketing",
  },
  {
    name: "Bill Hargrove",
    age: 71,
    job: "retired high-school football coach",
    lives_in: "Tulsa, Oklahoma",
    temperament: "loud, loyal, old-school",
    cares_about: "his former players, his church, his bad knees, Friday night games",
    how_they_read: "reads the headline on his phone and reacts; anything long he forwards to his wife to read, and anything he likes he forwards to twenty people",
  },
  {
    name: "Camille Dubois",
    age: 44,
    job: "cardiologist at a university hospital",
    lives_in: "Lyon, France",
    temperament: "rigorous, reserved, dislikes overstatement",
    cares_about: "her patients, evidence, her two daughters, her research group",
    how_they_read: "reads English medical literature daily on a desktop; marketing tone triggers immediate distrust, and she shares only peer-reviewed sources",
  },
  {
    name: "Emeka Nwosu",
    age: 38,
    job: "minibus driver on a city route",
    lives_in: "Enugu, Nigeria",
    temperament: "cheerful, pragmatic, always negotiating",
    cares_about: "fuel prices, full seats, the family's plot of land, his conductor's honesty",
    how_they_read: "reads English fine on his phone but scans only for the number and the catch; passes on anything that sounds like a deal to other drivers",
  },
  {
    name: "Susan Whitaker",
    age: 49,
    job: "residential real-estate agent",
    lives_in: "Charlotte, North Carolina",
    temperament: "upbeat, persuasive, always selling",
    cares_about: "closings, her clients, her tennis league, her online reviews",
    how_they_read: "reads for a hook on her phone and shares anything with energy; upbeat copy delights her rather than bothering her, and she posts constantly",
  },
  {
    name: "Viktor Petrov",
    age: 57,
    job: "mining engineer",
    lives_in: "Chelyabinsk, Russia",
    temperament: "stern, technical, suspicious of promises",
    cares_about: "mine safety, his crew, his summer dacha, his pension",
    how_they_read: "reads technical English on a desktop; sales language he reads as manipulation and stops reading, and he trusts numbers over words",
  },
  {
    name: "Leilani Kealoha",
    age: 30,
    job: "elementary-school teacher",
    lives_in: "Hilo, Hawaii",
    temperament: "warm, patient, community-first",
    cares_about: "her students, her extended family, the ocean, her school's garden",
    how_they_read: "reads with care on her phone and takes the tone personally, for better or worse; shares things that would help other teachers",
  },
  {
    name: "Arjun Mehta",
    age: 41,
    job: "IT consultant running his own firm",
    lives_in: "Bengaluru, India",
    temperament: "talkative, ambitious, deal-oriented",
    cares_about: "his clients, his children's schooling, cricket, his next contract",
    how_they_read: "reads fast on his phone, comfortable with jargon, hunts for the business value in any message, and forwards opportunities to his network",
  },
  {
    name: "Doris Fleming",
    age: 84,
    job: "retired English teacher",
    lives_in: "Kalamazoo, Michigan",
    temperament: "sharp, formal, patient",
    cares_about: "her church, her grandchildren, proper grammar, her weekly bridge game",
    how_they_read: "reads printed pages with a magnifier and email on a desktop; a typo or a missing comma lowers her opinion of the sender, and she does not trust the internet",
  },
  {
    name: "Mateo Rojas",
    age: 20,
    job: "food-delivery rider",
    lives_in: "Bogotá, Colombia",
    temperament: "restless, cheerful, focused on cash",
    cares_about: "his motorbike, his friends, his mother, the day's earnings",
    how_they_read: "reads Spanish on his phone between deliveries; English only when it is very short, and gives up otherwise, and shares memes with his friends",
  },
  {
    name: "Rebecca Stone",
    age: 34,
    job: "Presbyterian minister",
    lives_in: "Edinburgh, Scotland",
    temperament: "reflective, gentle, quietly stubborn",
    cares_about: "her congregation, justice for the poor, her allotment garden, her sermons",
    how_they_read: "reads for sincerity, often on paper, and notices manipulation, which disappoints her more than it angers her; shares things worth discussing",
  },
  {
    name: "Hiroshi Nakamura",
    age: 66,
    job: "retired bank branch manager",
    lives_in: "Nagoya, Japan",
    temperament: "formal, cautious, deliberate",
    cares_about: "his savings, his golf group, his grandchildren, his reputation",
    how_they_read: "reads English formally on a desktop; informal or urgent wording feels like a scam to him, and he confirms anything financial by telephone",
  },
  {
    name: "Chloe Bennett",
    age: 25,
    job: "nanny for two families",
    lives_in: "London, England",
    temperament: "kind, practical, tired",
    cares_about: "the children she looks after, her flatmates, saving for a trip to Portugal, her rent",
    how_they_read: "reads on the bus on her phone; short and friendly wins, long and formal gets ignored, and she shares things that make her laugh",
  },
  {
    name: "Amir Haddad",
    age: 39,
    job: "civil engineer specialising in bridges",
    lives_in: "Beirut, Lebanon",
    temperament: "resilient, sardonic, hard to impress",
    cares_about: "his projects, his family abroad, the electricity staying on, his firm surviving",
    how_they_read: "reads English fluently on a laptop and distrusts glossy promises from experience; shares dark jokes about bad news with friends",
  },
  {
    name: "Colleen Murphy",
    age: 53,
    job: "hospice nurse",
    lives_in: "Minneapolis, Minnesota",
    temperament: "compassionate, unflappable, direct",
    cares_about: "her patients' dignity, her team, her vegetable garden, her grown sons",
    how_they_read: "reads the whole message on her phone and judges the sender by their kindness to the reader; shares things that would comfort someone",
  },
  {
    name: "Dmitri Volkov",
    age: 29,
    job: "professional esports player",
    lives_in: "Kyiv, Ukraine",
    temperament: "competitive, blunt, online all day",
    cares_about: "winning, his team, his stream viewers, his sponsorship contract",
    how_they_read: "reads fast on two monitors, mocks hype, respects hard numbers, and roasts bad marketing live on stream",
  },
  {
    name: "Esperanza Villanueva",
    age: 60,
    job: "housekeeper for three families",
    lives_in: "Los Angeles, California",
    temperament: "hardworking, proud, quietly funny",
    cares_about: "the children of the families she works for, her own grown children, her church, her savings",
    how_they_read: "reads Spanish on her phone; English slowly and with help from her daughter, and she believes what her daughter tells her over what the message says",
  },
  {
    name: "Thomas Nkemelu",
    age: 48,
    job: "university lecturer in history",
    lives_in: "Pretoria, South Africa",
    temperament: "erudite, skeptical, dry",
    cares_about: "his students, evidence, a well-made argument, his book manuscript",
    how_they_read: "reads critically on a laptop and notices when a claim has no support behind it; shares articles with his colleagues along with a critique",
  },
  {
    name: "Emily Zhao",
    age: 16,
    job: "high-school sophomore",
    lives_in: "Fremont, California",
    temperament: "anxious, high-achieving, online",
    cares_about: "her grades, her friend group, her cat, getting into a good college",
    how_they_read: "reads quickly on her phone and worries about anything that sounds urgent or final; sends screenshots to her best friend to ask what they mean",
  },
  {
    name: "Hans Müller",
    age: 60,
    job: "master baker with his own shop",
    lives_in: "Munich, Germany",
    temperament: "early-rising, traditional, proud",
    cares_about: "bread quality, his apprentices, Bayern Munich, his shop's reputation",
    how_they_read: "reads German on paper and a phone; English only in short messages, and distrusts anything that sounds like advertising or comes from a big company",
  },
  {
    name: "Selin Yıldız",
    age: 27,
    job: "junior architect at a design studio",
    lives_in: "Istanbul, Turkey",
    temperament: "idealistic, stylish, sharp-tongued",
    cares_about: "good design, her city, her friends, her portfolio",
    how_they_read: "reads English well on her phone and laptop; notices when copy tries too hard and says so, and shares design she admires or ridicules",
  },
  {
    name: "Reginald Howard",
    age: 69,
    job: "retired postal carrier",
    lives_in: "Baltimore, Maryland",
    temperament: "steady, principled, dislikes being rushed",
    cares_about: "his pension, his block, jazz records, his grandchildren",
    how_they_read: "reads slowly and completely on a desktop; a rushed or pushy tone makes him dig in his heels, and he talks things over with his neighbours",
  },
  {
    name: "Anika Sharma",
    age: 35,
    job: "pediatrician at a group practice",
    lives_in: "Toronto, Canada",
    temperament: "warm, precise, quick to spot nonsense",
    cares_about: "her young patients, her parents, running, accurate health information",
    how_they_read: "reads for accuracy and safety on her phone, dismisses anything that overstates, and shares only what she would tell a patient",
  },
  {
    name: "Jorge Martínez",
    age: 44,
    job: "auto mechanic who owns his shop",
    lives_in: "El Paso, Texas",
    temperament: "plain-spoken, fair, tired of gimmicks",
    cares_about: "his customers, his crew, his three daughters, his shop's reputation",
    how_they_read: "reads short messages on his phone in English or Spanish; anything with 'limited time' in it he deletes on sight, and he never forwards ads",
  },
  {
    name: "Freya Jensen",
    age: 31,
    job: "wind-turbine technician",
    lives_in: "Aarhus, Denmark",
    temperament: "practical, adventurous, blunt",
    cares_about: "safety on the tower, climate, rock climbing, her team",
    how_they_read: "reads English at work every day on a rugged phone; wants the point, not the story, and shares only safety or climbing news",
  },
  {
    name: "Kofi Boateng",
    age: 55,
    job: "secondary-school mathematics teacher",
    lives_in: "Kumasi, Ghana",
    temperament: "patient, exact, respected in his town",
    cares_about: "his students passing their exams, his church, his small farm plot, his reputation",
    how_they_read: "reads formal English closely on his phone and expects precision from anyone writing to him; passes on serious information at church",
  },
  {
    name: "Lauren Fitzgerald",
    age: 29,
    job: "paralegal at a law firm",
    lives_in: "Boston, Massachusetts",
    temperament: "detail-oriented, anxious, a rule-follower",
    cares_about: "her career, her dog, true-crime podcasts, her student loans",
    how_they_read: "reads for fine print and consequences on a desktop and assumes she will be the one held responsible; forwards anything risky to her boss",
  },
  {
    name: "Ricardo Silva",
    age: 50,
    job: "dock worker at the port",
    lives_in: "Santos, Brazil",
    temperament: "strong, jovial, a union man",
    cares_about: "his workmates, Santos FC, his family, the union's next negotiation",
    how_they_read: "reads Portuguese on his phone; English almost not at all unless it is a number, and he passes anything about pay to the union",
  },
  {
    name: "Ayesha Malik",
    age: 40,
    job: "garment-factory line supervisor",
    lives_in: "Karachi, Pakistan",
    temperament: "firm, protective, careful with money",
    cares_about: "her workers, her children, her savings, her line hitting its targets",
    how_they_read: "reads Urdu on her phone; English slowly and mainly in short messages, and she asks her supervisor about anything official",
  },
  {
    name: "Brian Sullivan",
    age: 37,
    job: "police officer",
    lives_in: "Philadelphia, Pennsylvania",
    temperament: "guarded, sardonic, loyal",
    cares_about: "his partner, his family, his pension, his overtime",
    how_they_read: "reads on his phone for what the sender wants from him and assumes there is always something; shares only with his partner",
  },
  {
    name: "Nkechi Eze",
    age: 24,
    job: "fashion-design student",
    lives_in: "Lagos, Nigeria",
    temperament: "creative, outspoken, ambitious",
    cares_about: "her clothing brand, her Instagram, her sisters, her graduation collection",
    how_they_read: "reads fast on her phone, judges the tone, and reposts things she finds bold or funny; skips anything that looks corporate",
  },
  {
    name: "Stefan Weiss",
    age: 46,
    job: "Lutheran pastor",
    lives_in: "Leipzig, Germany",
    temperament: "thoughtful, measured, quietly funny",
    cares_about: "his parishioners, honesty, the refugee families he helps, his sermons",
    how_they_read: "reads English well on a laptop and weighs the intent behind words; shares things that would help the families he works with",
  },
  {
    name: "Maya Goldberg",
    age: 33,
    job: "founder of an education-technology startup",
    lives_in: "San Francisco, California",
    temperament: "driven, optimistic, fluent in startup jargon",
    cares_about: "her company, her team, her remaining runway, her investors' confidence",
    how_they_read: "skims on her phone for the ask and the number; forgives buzzwords and shares anything that sounds like momentum with her team",
  },
  {
    name: "Abdul Rahman",
    age: 58,
    job: "owner of a dry-goods shop",
    lives_in: "Peshawar, Pakistan",
    temperament: "hospitable, proud, cautious",
    cares_about: "his shop, his sons, his mosque, his suppliers' trust",
    how_they_read: "reads Urdu and Pashto on his phone; English rarely, and trusts a person he knows over any written message, so he asks his eldest son",
  },
  {
    name: "Patricia Alvarez",
    age: 62,
    job: "court interpreter",
    lives_in: "San Diego, California",
    temperament: "precise, patient, bilingual",
    cares_about: "accuracy, her grandchildren, salsa dancing, her pension",
    how_they_read: "reads every word in two languages on a tablet and catches ambiguity most people miss; shares only what she has checked herself",
  },
  {
    name: "Owen Hughes",
    age: 42,
    job: "hill sheep farmer",
    lives_in: "Snowdonia, Wales",
    temperament: "quiet, weather-hardened, stubborn",
    cares_about: "the flock, the land, his rugby club, his father's health",
    how_they_read: "reads Welsh and English on a phone with poor signal; ignores anything that is not about farming, weather, or family, and rarely replies",
  },
  {
    name: "Sunita Patel",
    age: 47,
    job: "owner of a roadside motel",
    lives_in: "Tucumcari, New Mexico",
    temperament: "hardworking, practical, welcoming",
    cares_about: "occupancy, her kids' college tuition, her town, her online reviews",
    how_they_read: "reads reservation emails all day on a desktop at the front desk; wants dates, prices, and clear terms, and nothing else, and forwards useful things to her husband",
  },
  {
    name: "Julien Moreau",
    age: 36,
    job: "sommelier at a restaurant",
    lives_in: "Paris, France",
    temperament: "refined, opinionated, a little snobbish",
    cares_about: "wine, craft, good conversation, the restaurant's reputation",
    how_they_read: "reads English well on his phone; hype and exclamation marks read as vulgar to him, and he mocks bad copy with colleagues",
  },
];
